### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by rchoudhary** [micromatch/glob-fs#10]
When trying to run the sync example from the website, I get the following error:

```
    return fp.split('\\').join('/');
             ^

TypeError: Cannot read property 'split' of undefined
```

For reference, here is the code:

```
var glob = require('glob-fs')({ gitignore: true });

var files = glob.readdirSync('**/*.js');
console.log(files);
```

My hunch is it involves line 74 of glob-fs/lib/pattern.js: `this.base = path.join(this.cwd, this.parent);`. Running the debugger, the `path.join` returns a nonsense path (the c:/ drive is in both `this.cwd` and `this.parent` and `path.join` just smashes them together). 

Even if I fix the issue of `this.pattern.re` vs `this.pattern.regex`, I still get the same 'fp is undefined' error.

**Comment by TimMurphy** [comment]
Same here.

**Comment by code-mattclaffey** [comment]
I get this error to

**Comment by paulcrussell** [comment]
Happening for me as well.

```
Globbing with **\*
C:\Users\paulr\node_modules\micromatch\lib\utils.js:66
    return fp.split('\\').join('/');
              ^

TypeError: fp.split is not a function
    at Object.unixify (C:\Users\paulr\node_modules\micromatch\lib\utils.js:66:15)
    at Function.any (C:\Users\paulr\node_modules\micromatch\index.js:231:14)
    at isMatch (C:\Users\paulr\node_modules\glob-fs-gitignore\index.js:16:17)
    at Object.gitignore (C:\Users\paulr\node_modules\glob-fs-gitignore\index.js:32:9)
    at Handler.handle (C:\Users\paulr\node_modules\glob-fs\lib\handler.js:26:17)
    at Object.Emitter.handle (C:\Users\paulr\node_modules\glob-fs\index.js:249:18)
    at C:\Users\paulr\node_modules\glob-fs\lib\iterators.js:168:20
    at C:\Users\paulr\node_modules\glob-fs\lib\symlinks.js:28:18
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by gbaumgart** [comment]
yes, how to set the root?

**Comment by gbaumgart** [comment]
however, this library just doesn't work on windows. no matter what you try, with exactly the same error

**Comment by setriosdomain** [comment]
Yes It works ok on linux and mac, but not on windows. Im getting this exact error when performing any search.

**Comment by setriosdomain** [comment]
on the setPattern function at index.js of the lib

change from
    // if middleware are registered, use the glob, otherwise regex
    var glob = this.fns.length
      ? this.pattern.glob
      : this.pattern.re;

to

```
// if middleware are registered, use the glob, otherwise regex
var glob = this.fns.length
  ? this.pattern.glob
  : this.pattern.regex;
```

this seems to fix the prob

**Comment by jonschlinkert** [comment]
sorry all, I think I mentioned this elsewhere but this might be fixed by updating micromatch to the latest version. I can do this when I have a chance, or if someone wants to do a pr I'd be happy to merge

**Comment by dynajoe** [comment]
Updating micromatch resulted same issue.

**Comment by Dan9boi** [comment]
+1 for this issue :(

**Comment by nowindowsowrking** [comment]
@rchoudhary @TimMurphy  @code-mattclaffey @paulcrussell  @gbaumgart 
This isn't anything new. All of @jonschlinkert repos doesn't work on windows and the author doesn't seem to won't to fix it either. Instead of giving replies, he lock thes the issue for collaborators only and doesn't reply.

When I pointed this out for him, he just blocked me from his repos! He doesn't like the truth to come out!!. So I suggest to you all, spread the words!!

See this issues as well: 
https://github.com/jonschlinkert/bash-glob/issues/1
https://github.com/jonschlinkert/nanomatch/issues/1

@jonschlinkert @doowb Any progress on this issue??

**Comment by octachrome** [comment]
I am getting the same error. This looks like a great library, more flexible than https://github.com/isaacs/node-glob, but it just doesn't work on Windows for a lot of people. Any chance of getting this fixed?

**Comment by jonschlinkert** [comment]
@octachrome, please see the very top of the front page of the project where it states `... This library is experimental and does not work on windows!`

> Any chance of getting this fixed?

We're going to do a complete refactor of this lib as soon as we have a chance. I'm not sure when that will be, but I'll make sure to publish the refactor on the `dev` branch and post an update here as soon as it's started

**Comment by itslenny** [comment]
It's exactly what @setriosdomain  suggested above. It's just a typo pattern.re is undefined it is supposed to be pattern.regex

**Comment by jonschlinkert** [comment]
@itslenny if you want to do a pr, I'll merge it in right away. That would make it a lot easier for me to get to this. Otherwise it might be a while

**Comment by itslenny** [comment]
I just tried it, but the issue seems to cascade a bit, and I'm honestly not sure where the rabbit hole ends.

When it gets the pattern correctly it winds up passing an array into gitignore instead of a string that gets passed to minimatch which calls `.split` on an array and crashes.

I updated the minimatch version which fixes that, but then I get an expected string error from `normalize-path` which is a sub-dependency of minimatch.

**Comment by jonschlinkert** [comment]
> I just tried it, but the issue seems to cascade a bit, and I'm honestly not sure where the rabbit hole ends.

Oh ok, you said "It's exactly what @setriosdomain suggested above. It's just a typo pattern.re is undefined it is supposed to be pattern.regex", so I thought you knew something I didn't. Thanks for clarifying.

**Comment by danielfaust** [comment]
How about adding a note on npmjs.com that this does not work on windows...

**Comment by startupsandcode** [comment]
I submitted a PR for this: https://github.com/micromatch/glob-fs/compare/master...lotekmedia:master
It definitely works on Windows now.  Thanks!

**Comment by jonschlinkert** [comment]
resolved by https://github.com/micromatch/glob-fs/pull/20
