### ISSUE TITLE
readdirSync is not a function

### ISSUE THREAD

**Issue by applemate** [micromatch/glob-fs#15]
error: /Users/craigcosmo/Desktop/electron skeleton/webpack.config.babel.js:49
var files = _globFs2.default.readdirSync('*.js');
                             ^

TypeError: _globFs2.default.readdirSync is not a function

Reproduce

```
import fs from 'fs'
import glob from 'glob-fs'
let files = glob.readdirSync('*.js');

console.log(files)
```

**Comment by jonschlinkert** [comment]
Do you have an example of how to reproduce the bug with code that doesn't need to be transpiled?

**Comment by applemate** [comment]
Does the package work with es6?

**Comment by jonschlinkert** [comment]
I was referring to this:

> error: /Users/craigcosmo/Desktop/electron skeleton/webpack.config.babel.js:49

How are webpack and babel related to this lib or the example? Or was that part irrelevant?

**Comment by applemate** [comment]
I wanted to get the folder structure (using your package) so I can use the structure in webpack modulesdirectories.

I was trying to produce something like this `['app', 'app/image', 'app/image/icon', 'dist', 'app/component']` , because this array is something webpack modulesdirectoris is expecting to receive.

I solved this. Like this http://stackoverflow.com/questions/39674832/nodejs-get-folder-structure-recursively-and-synchronously?noredirect=1#comment66650122_39674832

**Comment by jonschlinkert** [comment]
Oh ok, thanks for clarifying
