### ISSUE TITLE
micromatch dependancy pulls from github not npm

### ISSUE THREAD

**Issue by gaje** [micromatch/glob-fs#17]
The dependency for: `"micromatch": "jonschlinkert/micromatch#2.2.0"`, pulls from github repo instead of npm. This breaks on firewalled networks that do not have access to public github. Can this be changed to pull from npm instead?

**Comment by jonschlinkert** [comment]
sure, but we'd need to make sure the tests are passing. fwiw this lib is being refactored anyway

**Comment by misterbrownlee** [comment]
This makes glob-fs a no go for us on a project.  Too bad, it seems like a good start

**Comment by tunnckoCore** [comment]
@misterbrownlee it seems, but it isn't ready enough for "production" or whatever you wanna call it, because it is not very stable at this moment. But yea, it is great. :)

**Comment by jonschlinkert** [comment]
closing, we're working on the next version and won't be making any changes to this branch
